<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Animal;
use App\Models\Habitat;

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Query habitats to map dynamically
        $rainforest = Habitat::where('name', 'Amazon Rainforest')->first();
        $tundra = Habitat::where('name', 'Arctic Tundra')->first();
        $jungle = Habitat::where('name', 'Asian Jungle')->first();
        $desert = Habitat::where('name', 'Sahara Desert')->first();
        $aviary = Habitat::where('name', 'Tropical Aviary')->first();
        $reef = Habitat::where('name', 'Coral Reef')->first();

        $rainforestId = $rainforest ? $rainforest->id : 1;
        $tundraId = $tundra ? $tundra->id : 2;
        $jungleId = $jungle ? $jungle->id : 3;
        $desertId = $desert ? $desert->id : 4;
        $aviaryId = $aviary ? $aviary->id : 5;
        $reefId = $reef ? $reef->id : 6;

        $animals = [
            // --- AMAZON RAINFOREST ANIMALS ---
            [
                'name' => 'Capybara',
                'scientific_name' => 'Hydrochoerus hydrochaeris',
                'habitat_id' => $rainforestId,
                'type' => 'mammal',
                'diet' => 'herbivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 50.0,
                'lifespan_years' => 10,
                'speed_kmh' => 35.0,
                'fun_fact' => 'Capybaras are the world\'s largest rodents and are excellent swimmers with webbed feet.',
                'description' => 'Highly social semi-aquatic rodents that live in large groups along the rivers of the Amazon rainforest.',
                'image_path' => '/images/Amazon Rainforest Animals/Capybara.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Jaguar',
                'scientific_name' => 'Panthera onca',
                'habitat_id' => $rainforestId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Vulnerable',
                'weight_kg' => 95.0,
                'lifespan_years' => 15,
                'speed_kmh' => 80.0,
                'fun_fact' => 'Jaguars have an exceptionally powerful bite that can pierce the shells of turtles and tortoises.',
                'description' => 'The largest big cat in the Americas, known for its beautiful rosette pattern and love of swimming.',
                'image_path' => '/images/Amazon Rainforest Animals/Jaguar.jpg',
                'is_featured' => true,
            ],
            [
                'name' => 'Pink River Dolphin',
                'scientific_name' => 'Inia geoffrensis',
                'habitat_id' => $rainforestId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Endangered',
                'weight_kg' => 150.0,
                'lifespan_years' => 30,
                'speed_kmh' => 22.0,
                'fun_fact' => 'They can turn their necks 180 degrees, allowing them to navigate through flooded tree trunks.',
                'description' => 'Also known as the boto, this freshwater dolphin changes color with age, becoming vibrant pink as it matures.',
                'image_path' => '/images/Amazon Rainforest Animals/Pink River Dolphin.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Sloth',
                'scientific_name' => 'Bradypus tridactylus',
                'habitat_id' => $rainforestId,
                'type' => 'mammal',
                'diet' => 'herbivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 4.5,
                'lifespan_years' => 30,
                'speed_kmh' => 0.25,
                'fun_fact' => 'Sloths can hold their breath longer than dolphins—up to 40 minutes—by slowing down their heart rate.',
                'description' => 'Extremely slow-moving mammals that spend almost their entire lives hanging upside down in the forest canopy.',
                'image_path' => '/images/Amazon Rainforest Animals/Sloth.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Spider Monkey',
                'scientific_name' => 'Ateles geoffroyi',
                'habitat_id' => $rainforestId,
                'type' => 'mammal',
                'diet' => 'omnivore',
                'conservation_status' => 'Endangered',
                'weight_kg' => 8.5,
                'lifespan_years' => 25,
                'speed_kmh' => 55.0,
                'fun_fact' => 'Spider monkeys use their prehensile tail as a fifth limb to grip branches and swing gracefully.',
                'description' => 'Highly agile primates that inhabit the high canopy layers, known for their long limbs and loud calls.',
                'image_path' => '/images/Amazon Rainforest Animals/Spider Monkey.jpg',
                'is_featured' => false,
            ],

            // --- ARCTIC TUNDRA ANIMALS ---
            [
                'name' => 'Arctic Fox',
                'scientific_name' => 'Vulpes lagopus',
                'habitat_id' => $tundraId,
                'type' => 'mammal',
                'diet' => 'omnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 3.5,
                'lifespan_years' => 6,
                'speed_kmh' => 50.0,
                'fun_fact' => 'Their fur changes color with the seasons: pure white in winter, and brown-gray in summer.',
                'description' => 'A small, incredibly hardy fox that thrives in the extreme cold temperatures of the Arctic tundra.',
                'image_path' => '/images/arctic tundra animals/arctic fox.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Penguin',
                'scientific_name' => 'Aptenodytes forsteri',
                'habitat_id' => $tundraId,
                'type' => 'bird',
                'diet' => 'carnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 30.0,
                'lifespan_years' => 20,
                'speed_kmh' => 10.0,
                'fun_fact' => 'Emperor penguins can dive to depths of over 500 meters and hold their breath for up to 22 minutes.',
                'description' => 'Flightless birds adapted to life in the freezing waters of the Antarctic and sub-Arctic regions.',
                'image_path' => '/images/arctic tundra animals/penguin.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Polar Bear',
                'scientific_name' => 'Ursus maritimus',
                'habitat_id' => $tundraId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Vulnerable',
                'weight_kg' => 450.0,
                'lifespan_years' => 25,
                'speed_kmh' => 40.0,
                'fun_fact' => 'Polar bear skin is actually black, and their hollow fur reflects light to appear white.',
                'description' => 'Massive marine mammals perfectly adapted to the freezing temperatures, sea ice, and cold waters of the Arctic circle.',
                'image_path' => '/images/arctic tundra animals/polar bear.jpg',
                'is_featured' => true,
            ],
            [
                'name' => 'Snow Leopard',
                'scientific_name' => 'Panthera uncia',
                'habitat_id' => $tundraId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Vulnerable',
                'weight_kg' => 55.0,
                'lifespan_years' => 15,
                'speed_kmh' => 64.0,
                'fun_fact' => 'Snow leopards cannot roar; they make a non-aggressive puffing sound called a chuff.',
                'description' => 'A beautiful, elusive big cat adapted to the cold, rugged mountain ranges of Central Asia.',
                'image_path' => '/images/arctic tundra animals/snow leopard.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Walrus',
                'scientific_name' => 'Odobenus rosmarus',
                'habitat_id' => $tundraId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Vulnerable',
                'weight_kg' => 1000.0,
                'lifespan_years' => 40,
                'speed_kmh' => 35.0,
                'fun_fact' => 'Walruses use their long tusks to pull themselves out of the water onto the ice.',
                'description' => 'Large marine mammals recognized by their prominent tusks, whiskers, and bulky bodies.',
                'image_path' => '/images/arctic tundra animals/walrus.jpg',
                'is_featured' => false,
            ],

            // --- ASIAN JUNGLE ANIMALS ---
            [
                'name' => 'Elephant',
                'scientific_name' => 'Elephas maximus',
                'habitat_id' => $jungleId,
                'type' => 'mammal',
                'diet' => 'herbivore',
                'conservation_status' => 'Endangered',
                'weight_kg' => 4000.0,
                'lifespan_years' => 60,
                'speed_kmh' => 40.0,
                'fun_fact' => 'Asian elephants have smaller ears than their African cousins and have a single finger-like process on the tip of their trunks.',
                'description' => 'Highly intelligent, emotional giants that live in structured matriarchal herds in forests and grasslands.',
                'image_path' => '/images/Asian jungle animals/elephant.jpg',
                'is_featured' => true,
            ],
            [
                'name' => 'Gorilla',
                'scientific_name' => 'Gorilla beringei',
                'habitat_id' => $jungleId,
                'type' => 'mammal',
                'diet' => 'herbivore',
                'conservation_status' => 'Critically Endangered',
                'weight_kg' => 160.0,
                'lifespan_years' => 40,
                'speed_kmh' => 40.0,
                'fun_fact' => 'Gorillas share about 98.3% of their DNA with humans, making them some of our closest living relatives.',
                'description' => 'Powerful, intelligent, and gentle giants that live in structured family groups led by a silverback male gorilla.',
                'image_path' => '/images/Asian jungle animals/gorilla.jpg',
                'is_featured' => true,
            ],
            [
                'name' => 'Leopard',
                'scientific_name' => 'Panthera pardus',
                'habitat_id' => $jungleId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Vulnerable',
                'weight_kg' => 60.0,
                'lifespan_years' => 15,
                'speed_kmh' => 58.0,
                'fun_fact' => 'Leopards are excellent climbers and drag heavy prey up trees to keep it away from scavengers.',
                'description' => 'Graceful and powerful big cats known for their stealth, agility, and beautiful spotted coats.',
                'image_path' => '/images/Asian jungle animals/leopard.jpg',
                'is_featured' => true,
            ],
            [
                'name' => 'Monkey',
                'scientific_name' => 'Macaca mulatta',
                'habitat_id' => $jungleId,
                'type' => 'mammal',
                'diet' => 'omnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 7.0,
                'lifespan_years' => 25,
                'speed_kmh' => 32.0,
                'fun_fact' => 'Some monkey species use tools like rocks to crack open nuts and shells.',
                'description' => 'Highly social and active primates that live in forests, navigating the canopy with ease.',
                'image_path' => '/images/Asian jungle animals/monkey.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Red Panda',
                'scientific_name' => 'Ailurus fulgens',
                'habitat_id' => $jungleId,
                'type' => 'mammal',
                'diet' => 'herbivore',
                'conservation_status' => 'Endangered',
                'weight_kg' => 5.0,
                'lifespan_years' => 10,
                'speed_kmh' => 24.0,
                'fun_fact' => 'Red pandas have a false thumb, which is an extension of the wrist bone used to grip bamboo.',
                'description' => 'Small, tree-dwelling mammals native to the eastern Himalayas, with reddish-brown fur and a long, shaggy tail.',
                'image_path' => '/images/Asian jungle animals/red-panda.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Tiger',
                'scientific_name' => 'Panthera tigris',
                'habitat_id' => $jungleId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Endangered',
                'weight_kg' => 220.0,
                'lifespan_years' => 15,
                'speed_kmh' => 65.0,
                'fun_fact' => 'No two tigers have the exact same pattern of stripes, much like human fingerprints.',
                'description' => 'An iconic striped predator of the Asian continent, tiger populations are carefully protected in national parks.',
                'image_path' => '/images/Asian jungle animals/tiger.jpg',
                'is_featured' => true,
            ],

            // --- SAHARA DESERT ANIMALS ---
            [
                'name' => 'Addax Antelope',
                'scientific_name' => 'Addax nasomaculatus',
                'habitat_id' => $desertId,
                'type' => 'mammal',
                'diet' => 'herbivore',
                'conservation_status' => 'Critically Endangered',
                'weight_kg' => 100.0,
                'lifespan_years' => 19,
                'speed_kmh' => 50.0,
                'fun_fact' => 'Addax antelopes rarely need to drink water, obtaining moisture almost entirely from the vegetation they eat.',
                'description' => 'A critically endangered desert antelope with long, spiral horns and a light-colored coat that reflects desert heat.',
                'image_path' => '/images/Sahara Desert Animals/Addax Antelope.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'African Wildcat',
                'scientific_name' => 'Felis lybica',
                'habitat_id' => $desertId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 4.5,
                'lifespan_years' => 12,
                'speed_kmh' => 48.0,
                'fun_fact' => 'The African wildcat is the direct ancestor of all domestic housecats.',
                'description' => 'A stealthy, nocturnal hunter that preys on rodents, birds, and insects in the desert brush.',
                'image_path' => '/images/Sahara Desert Animals/African Wildcat.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Dromedary Camel',
                'scientific_name' => 'Camelus dromedarius',
                'habitat_id' => $desertId,
                'type' => 'mammal',
                'diet' => 'herbivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 500.0,
                'lifespan_years' => 40,
                'speed_kmh' => 65.0,
                'fun_fact' => 'A camel\'s hump stores fat, not water, which serves as a vital energy source during long desert travels.',
                'description' => 'The classic single-humped camel, legendary for its endurance and ability to withstand extreme heat and dehydration.',
                'image_path' => '/images/Sahara Desert Animals/Dromedary Camel.jpg',
                'is_featured' => true,
            ],
            [
                'name' => 'Fennec Fox',
                'scientific_name' => 'Vulpes zerda',
                'habitat_id' => $desertId,
                'type' => 'mammal',
                'diet' => 'omnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 1.3,
                'lifespan_years' => 10,
                'speed_kmh' => 40.0,
                'fun_fact' => 'Their enormous ears serve dual purposes: dissipating body heat to keep cool and listening for underground prey.',
                'description' => 'The smallest of all canine species, easily recognizable by its oversized ears and light-colored sandy coat.',
                'image_path' => '/images/Sahara Desert Animals/Fennec Fox.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Jerboa',
                'scientific_name' => 'Jaculus jaculus',
                'habitat_id' => $desertId,
                'type' => 'mammal',
                'diet' => 'herbivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 0.05,
                'lifespan_years' => 6,
                'speed_kmh' => 24.0,
                'fun_fact' => 'Jerboas can hop like miniature kangaroos, jumping up to three meters in a single bound to escape predators.',
                'description' => 'Tiny, hopping desert rodents with long hind legs and tails, active mostly during the cooler desert nights.',
                'image_path' => '/images/Sahara Desert Animals/Jerboa.jpg',
                'is_featured' => false,
            ],

            // --- TROPICAL AVIARY ANIMALS ---
            [
                'name' => 'Eagle',
                'scientific_name' => 'Aquila chrysaetos',
                'habitat_id' => $aviaryId,
                'type' => 'bird',
                'diet' => 'carnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 4.5,
                'lifespan_years' => 20,
                'speed_kmh' => 160.0,
                'fun_fact' => 'Eagles have incredible vision, allowing them to spot prey from miles away.',
                'description' => 'Large, powerful birds of prey with hooked beaks and strong talons, soaring high in the skies.',
                'image_path' => '/images/Tropical Aviary Animals/eagle.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Macaw',
                'scientific_name' => 'Ara macao',
                'habitat_id' => $aviaryId,
                'type' => 'bird',
                'diet' => 'omnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 1.2,
                'lifespan_years' => 50,
                'speed_kmh' => 56.0,
                'fun_fact' => 'Macaws use their strong beaks to crack open hard nutshells and lick clay deposits.',
                'description' => 'Stunningly colorful parrots native to tropical rainforests, known for their high intelligence and loud vocalizations.',
                'image_path' => '/images/Tropical Aviary Animals/macaw.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Owl',
                'scientific_name' => 'Bubo virginianus',
                'habitat_id' => $aviaryId,
                'type' => 'bird',
                'diet' => 'carnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 1.5,
                'lifespan_years' => 10,
                'speed_kmh' => 40.0,
                'fun_fact' => 'Owls can rotate their heads up to 270 degrees without breaking blood vessels.',
                'description' => 'Nocturnal birds of prey with specialized feathers that enable silent flight.',
                'image_path' => '/images/Tropical Aviary Animals/owl.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Peacock',
                'scientific_name' => 'Pavo cristatus',
                'habitat_id' => $aviaryId,
                'type' => 'bird',
                'diet' => 'omnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 4.0,
                'lifespan_years' => 15,
                'speed_kmh' => 16.0,
                'fun_fact' => 'Only the males (peacocks) have the beautiful colorful train of feathers; females are called peahens.',
                'description' => 'Large, colorful pheasants famous for their iridescent blue and green tail feathers.',
                'image_path' => '/images/Tropical Aviary Animals/peacock.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Toucan',
                'scientific_name' => 'Ramphastos toco',
                'habitat_id' => $aviaryId,
                'type' => 'bird',
                'diet' => 'omnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 0.6,
                'lifespan_years' => 20,
                'speed_kmh' => 38.0,
                'fun_fact' => 'A toucan\'s giant beak is actually lightweight and helps regulate their body temperature.',
                'description' => 'Brightly colored forest birds recognized by their oversized, colorful bills.',
                'image_path' => '/images/Tropical Aviary Animals/toucan.jpg',
                'is_featured' => false,
            ],

            // --- CORAL REEF ANIMALS ---
            [
                'name' => 'Dolphin',
                'scientific_name' => 'Tursiops truncatus',
                'habitat_id' => $reefId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 200.0,
                'lifespan_years' => 40,
                'speed_kmh' => 45.0,
                'fun_fact' => 'Dolphins have names for each other, using unique whistles to call and reference individual companions.',
                'description' => 'Highly intelligent and playful marine mammals that swim in cooperative pods and communicate with clicking sounds.',
                'image_path' => '/images/coral reef animals/dolphin.jpg',
                'is_featured' => true,
            ],
            [
                'name' => 'Jellyfish',
                'scientific_name' => 'Aurelia aurita',
                'habitat_id' => $reefId,
                'type' => 'fish',
                'diet' => 'carnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 0.2,
                'lifespan_years' => 1,
                'speed_kmh' => 8.0,
                'fun_fact' => 'Jellyfish are made of 95% water and have no brains, hearts, bones, or eyes.',
                'description' => 'Gelatinous, free-swimming marine creatures with trailing tentacles equipped with stinging cells.',
                'image_path' => '/images/coral reef animals/jellyfish.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Octopus',
                'scientific_name' => 'Octopus vulgaris',
                'habitat_id' => $reefId,
                'type' => 'fish',
                'diet' => 'carnivore',
                'conservation_status' => 'Least Concern',
                'weight_kg' => 15.0,
                'lifespan_years' => 3,
                'speed_kmh' => 40.0,
                'fun_fact' => 'Octopuses have three hearts, blue blood, and can squeeze through tiny spaces.',
                'description' => 'Highly intelligent, eight-armed cephalopods known for their camouflage and problem-solving skills.',
                'image_path' => '/images/coral reef animals/octupus.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Sea Turtle',
                'scientific_name' => 'Chelonia mydas',
                'habitat_id' => $reefId,
                'type' => 'reptile',
                'diet' => 'omnivore',
                'conservation_status' => 'Endangered',
                'weight_kg' => 130.0,
                'lifespan_years' => 80,
                'speed_kmh' => 35.0,
                'fun_fact' => 'Sea turtles return to the exact same beach where they were born to lay their own eggs.',
                'description' => 'Ancient marine reptiles that spend their lives swimming across the world\'s oceans.',
                'image_path' => '/images/coral reef animals/turtle.jpg',
                'is_featured' => false,
            ],
            [
                'name' => 'Whale',
                'scientific_name' => 'Balaenoptera musculus',
                'habitat_id' => $reefId,
                'type' => 'mammal',
                'diet' => 'carnivore',
                'conservation_status' => 'Endangered',
                'weight_kg' => 120000.0,
                'lifespan_years' => 90,
                'speed_kmh' => 30.0,
                'fun_fact' => 'A blue whale\'s tongue can weigh as much as an entire elephant!',
                'description' => 'Earth\'s largest marine mammals, navigating the oceans and communicating through complex songs.',
                'image_path' => '/images/coral reef animals/whale.jpg',
                'is_featured' => true,
            ],
        ];

        foreach ($animals as $animal) {
            Animal::updateOrCreate(['name' => $animal['name']], $animal);
        }
    }
}
